### ISSUE TITLE
promtail sidecar causing issue 

### ISSUE THREAD

**Issue by rajeshkbathula** [mhus/mhus-docker#1]
**standard_init_linux.go:228: exec user process caused: permission denied**

```
      - name: promtail-container
        image: mhus/promtail-sidecar:1.0.0
        env:
          - name: LOG_NS
            value: "airflow"
          - name: LOG_JOB
            value: "scheduler"
          - name: LOG_FILE_PATH
            value: "/usr/local/airflow/logs/dag_processor_manager/*.log"
          - name: LOG_URL
            value: "http://dev-eks-loki:3100/loki/api/v1/push"
        volumeMounts:
          - name: shared-logs
            mountPath: /usr/local/airflow/logs/dag_processor_manager
    extraVolumeMounts:
      # - volumeMounts:
      - name: shared-logs
        mountPath: /usr/local/airflow/logs/dag_processor_manager

```
